/* eslint-disable @medusajs/prices-in-major-units -- IRR is stored as an integer in this storefront. */
import { MedusaContainer } from "@medusajs/framework"
import { ContainerRegistrationKeys, Modules, ProductStatus } from "@medusajs/framework/utils"
import type { IPromotionModuleService } from "@medusajs/framework/types"
import {
  createPromotionsWorkflow,
  createProductCategoriesWorkflow,
  createProductOptionsWorkflow,
  createProductsWorkflow,
  deleteProductCategoriesWorkflow,
  deleteProductOptionsWorkflow,
  deleteProductsWorkflow,
  updateRegionsWorkflow,
} from "@medusajs/medusa/core-flows"

const storefrontImageBase = "http://localhost:8000/images/3dmorty/catalog"

// This campaign powers the countdown on the storefront. Keep its end date in
// sync with `home-promotion-countdown` when planning the next launch offer.
const launchPromotion = {
  code: "MORTY15",
  startsAt: "2026-09-11T00:00:00.000Z",
  endsAt: "2026-09-14T20:59:59.000Z",
}

async function ensureLaunchPromotion(container: MedusaContainer, logger: { info: (message: string) => void }) {
  const promotionService = container.resolve<IPromotionModuleService>(Modules.PROMOTION)
  const existing = await promotionService.listPromotions({ code: launchPromotion.code })

  if (existing.length > 0) {
    logger.info(`3DMorty launch promotion ${launchPromotion.code} already exists.`)
    return
  }

  await createPromotionsWorkflow(container).run({
    input: {
      promotionsData: [{
        code: launchPromotion.code,
        type: "standard",
        status: "active",
        is_automatic: false,
        application_method: {
          type: "percentage",
          target_type: "order",
          allocation: "across",
          value: 15,
          currency_code: "irr",
        },
        campaign: {
          name: "3DMorty launch offer",
          description: "15% limited launch offer shown on the 3DMorty home page.",
          campaign_identifier: "3dmorty:launch-morty15",
          starts_at: new Date(launchPromotion.startsAt),
          ends_at: new Date(launchPromotion.endsAt),
        },
      }],
    },
  })

  logger.info(`3DMorty launch promotion ${launchPromotion.code} is active until ${launchPromotion.endsAt}.`)
}

type Category = "figures-collectibles" | "desk-gaming" | "organizers-decor" | "gift-hair-accessories"
type CatalogProduct = {
  title: string; handle: string; short: string; description: string; category: Category
  type: string; sku: string; price: number; images: string[]; material: string; color: string
  style: string; dimensions: string; useCases: string; care: string; tags: string[]; features: string[]
  character?: string
}

// Keep generated catalog imagery as the first image when the seed is rerun.
// The original studio shots remain in the gallery as alternate product views.
const generatedPrimaryImages: Record<string, string> = {
  "spiky-anime-head-bust": "generated/spiky-anime-bust-color.png",
  "winged-serpent-staff": "generated/winged-serpent-staff-color.png",
  "playstation-controller-stands": "generated/playstation-controller-stands-color.png",
  "masked-tactical-soldier-figure": "generated/tactical-soldier-color.png",
  "cartoon-goose-figure": "generated/cartoon-goose-figure-color.png",
  "gothic-skull-rod-holder": "generated/gothic-skull-rod-holder-color.png",
  "viking-warrior-bust": "generated/viking-warrior-bust-color.png",
  "luffy-straw-hat-anime-bust": "generated/straw-hat-anime-bust-color.png",
  "owl-wing-collector-wreath": "generated/owl-wing-collector-wreath-color.png",
  "germany-football-controller-stand": "generated/fc26-germany-controller-stand-color.png",
  "scream-can-holder": "generated/scream-can-holder-color.png",
  "sisyphus-collector-tray": "generated/sisyphus-collector-tray-color.png",
  "soccer-ball-headset-stand": "generated/soccer-ball-headset-stand-color.png",
  "world-cup-controller-stand": "generated/world-cup-controller-stand-color.png",
}

const product = (item: CatalogProduct) => {
  const generatedImage = generatedPrimaryImages[item.handle]

  if (!generatedImage || item.images.includes(generatedImage)) {
    return item
  }

  return { ...item, images: [generatedImage, ...item.images] }
}

const printTechnology = (material: string) =>
  material.includes("رزین") ? "Resin" : "FDM"

const compatibilityFor = (item: CatalogProduct) => {
  const knownCompatibility = item.tags.find((tag) =>
    /PS5|DualSense|Xbox|Nintendo|کنترلر|هدست/i.test(tag)
  )

  return knownCompatibility || undefined
}

const products = [
  product({ title: "فیگور کیتسونه مفصلی صورتی", handle: "pink-kitsune-articulated-figure", short: "ست فیگور کیتسونه با دم‌های لایه‌ای و ظاهر فانتزی.", description: "فیگور کیتسونه مفصلی با ترکیب صورتی و سفید، جزئیات صورت بازیگوش و دم‌های لایه‌ای طراحی شده است. انتخابی چشم‌گیر برای شلف کلکسیون، میز کار یا هدیه به علاقه‌مندان فیگورهای فانتزی.", category: "figures-collectibles", type: "فیگور مفصلی", sku: "3DM-FIG-001", price: 1890000, images: ["01-pink-kitsune-figures.png"], material: "پلاستیک چاپ سه‌بعدی", color: "صورتی و سفید", style: "فانتزی ژاپنی", dimensions: "اندازه دقیق هنگام ثبت سفارش هماهنگ می‌شود", useCases: "کلکسیون، دکور میز، هدیه", care: "با دستمال نرم و خشک تمیز شود؛ از فشار روی دم‌ها خودداری کنید.", tags: ["کیتسونه", "فیگور فانتزی", "چاپ سه‌بعدی", "هدیه"], features: ["طراحی چندبخشی", "بافت لایه‌ای چاپ", "ترکیب رنگ پاستلی"] }),
  product({ title: "گلدان رومیزی دست‌های قلبی", handle: "heart-hands-planter", short: "گلدان کوچک و دوست‌داشتنی با دست‌هایی که قلب می‌سازند.", description: "این گلدان رومیزی با چهره خندان و دست‌هایی که یک قلب می‌سازند، برای گیاهان کوچک و قلمه‌های سبک طراحی شده است. فرم نرم و مینیمال آن، میز کار، پنجره یا هدیه‌های صمیمی را گرم‌تر می‌کند.", category: "organizers-decor", type: "گلدان دکوراتیو", sku: "3DM-DEC-002", price: 790000, images: ["02-heart-hands-planter.png"], material: "پلاستیک چاپ سه‌بعدی", color: "سفید", style: "مینیمال فانتزی", dimensions: "مناسب گیاهان رومیزی کوچک", useCases: "میز کار، اتاق خواب، هدیه", care: "برای نگهداری گیاه از گلدان داخلی یا پوشش مناسب استفاده کنید.", tags: ["گلدان رومیزی", "دکور فانتزی", "هدیه"], features: ["چهره خندان", "فرم قلبی", "مناسب فضاهای کوچک"] }),
  product({ title: "چراغ روح با بادکنک قرمز", handle: "ghost-balloon-desk-lamp", short: "چراغ رومیزی فانتزی با نور گرم و بادکنک قرمز.", description: "چراغ روح کوچک با بادکنک قرمز، یک اکسسوری خاص برای اتاق گیمینگ، میز مطالعه یا گوشه کلکسیون است. نور گرم آن در کنار فرم دوست‌داشتنی روح، حال‌وهوایی سینمایی و بازیگوش به فضا می‌دهد.", category: "desk-gaming", type: "چراغ رومیزی دکوراتیو", sku: "3DM-LMP-003", price: 2490000, images: ["03-ghost-balloon-lamp.png"], material: "پلاستیک چاپ سه‌بعدی و قطعات روشنایی", color: "زرد گرم و قرمز", style: "فانتزی گیمینگ", dimensions: "ابعاد دقیق هنگام ثبت سفارش هماهنگ می‌شود", useCases: "میز گیمینگ، اتاق خواب، هدیه", care: "با پارچه خشک تمیز شود و از تماس با آب دور نگه داشته شود.", tags: ["چراغ روح", "اتاق گیمینگ", "دکور رومیزی"], features: ["نور گرم", "پایه ایستاده", "طراحی فانتزی"] }),
  product({ title: "فیگور سمور دریایی مفصلی", handle: "articulated-otter-figure", short: "فیگورهای سمور دریایی با مفصل‌های متحرک و بافت چاپی.", description: "فیگور سمور دریایی مفصلی با قطعه‌بندی انعطاف‌پذیر، ظاهر بامزه و جزئیات لایه‌ای چاپ سه‌بعدی ساخته شده است. می‌توانید آن را روی میز، کتابخانه یا کنار مانیتور قرار دهید و حالت دلخواهش را تنظیم کنید.", category: "figures-collectibles", type: "فیگور مفصلی", sku: "3DM-FIG-004", price: 990000, images: ["04-articulated-otters.png"], material: "پلاستیک چاپ سه‌بعدی", color: "سبز نعنایی یا خاکستری", style: "حیوانات فانتزی", dimensions: "ابعاد دقیق هنگام ثبت سفارش هماهنگ می‌شود", useCases: "کلکسیون، سرگرمی رومیزی، هدیه", care: "قطعه‌ها را آرام و بدون فشار ناگهانی جابه‌جا کنید.", tags: ["سمور", "فیگور مفصلی", "حیوان فانتزی"], features: ["بخش‌های متحرک", "جزئیات پنجه و دم", "مناسب هدیه"] }),
  product({ title: "کیف کارت کشویی اسلایدر", handle: "slidr-card-wallet", short: "کیف کارت باریک با مکانیزم کشویی و نمای مشبک.", description: "کیف کارت کشویی اسلایدر برای همراه‌داشتن چند کارت ضروری، با بدنه‌ای سبک و نمای مشبک طراحی شده است. مکانیزم کشویی دسترسی سریع‌تر به کارت‌ها را فراهم می‌کند و برای استفاده روزانه یا هدیه‌ای کاربردی مناسب است.", category: "desk-gaming", type: "اکسسوری روزمره", sku: "3DM-ACC-005", price: 690000, images: ["05-slidr-card-wallet.png"], material: "پلاستیک چاپ سه‌بعدی", color: "آبی خاکستری", style: "مدرن تکنولوژی", dimensions: "مناسب کارت‌های استاندارد بانکی", useCases: "استفاده روزمره، هدیه کاربردی", care: "از قرار دادن در گرمای مستقیم و فشار زیاد خودداری کنید.", tags: ["کیف کارت", "اکسسوری روزمره", "چاپ سه‌بعدی"], features: ["مکانیزم کشویی", "بدنه سبک", "بافت مشبک"] }),
  product({ title: "جا براشی گوتیک کرستی", handle: "gothic-corset-brush-holder", short: "نگهدارنده براش آرایشی با طراحی کرست گوتیک و جزئیات برجسته.", description: "جا براشی گوتیک کرستی، یک نظم‌دهنده رومیزی با فرم کرست، بندبندی برجسته و جزئیات تزئینی است. برای براش‌های آرایشی، قلم‌های طراحی یا ابزارهای سبک روی میز، انتخابی متفاوت و کلکسیونی به شمار می‌رود.", category: "organizers-decor", type: "نظم‌دهنده رومیزی", sku: "3DM-ORG-006", price: 1490000, images: ["06-gothic-corset-brush-holder.png"], material: "پلاستیک چاپ سه‌بعدی", color: "مشکی مات", style: "گوتیک", dimensions: "مناسب براش و قلم‌های رومیزی", useCases: "میز آرایش، میز هنری، هدیه گوتیک", care: "با برس نرم یا پارچه خشک، شیارهای تزئینی را تمیز کنید.", tags: ["گوتیک", "جا براشی", "نظم‌دهنده"], features: ["طرح کرست", "جزئیات برجسته", "کاربری چندمنظوره"] }),
  product({ title: "جا براشی پاپیون صورتی", handle: "pink-bow-brush-organizer", short: "نظم‌دهنده براش با پاپیون بزرگ و محفظه‌های کاربردی.", description: "این نظم‌دهنده صورتی با پاپیون برجسته، براش‌ها و ابزارهای آرایشی را مرتب و در دسترس نگه می‌دارد. ظاهر نرم و پاستلی آن برای میز آرایش، اتاق نوجوان یا هدیه‌های سلیقه‌ای بسیار مناسب است.", category: "organizers-decor", type: "نظم‌دهنده آرایشی", sku: "3DM-ORG-007", price: 1290000, images: ["07-pink-bow-brush-organizer.png"], material: "پلاستیک چاپ سه‌بعدی", color: "صورتی پاستلی", style: "کواِی و فانتزی", dimensions: "مناسب براش و لوازم آرایشی سبک", useCases: "میز آرایش، هدیه، نظم‌دهی رومیزی", care: "با دستمال نرم و کمی مرطوب تمیز و سپس خشک شود.", tags: ["جا براشی", "پاپیون", "صورتی"], features: ["پاپیون برجسته", "چند محفظه", "رنگ پاستلی"] }),
  product({ title: "جعبه جواهرات پاپیونی صورتی", handle: "pink-bow-jewelry-box", short: "جعبه گرد جواهرات با بدنه طرح‌دار و درِ پاپیونی.", description: "جعبه جواهرات گرد با بدنه‌ای طرح‌دار و درِ پاپیونی، راهی دلنشین برای نگهداری زیورآلات کوچک و یادگاری‌هاست. ترکیب صورتی پاستلی و فرم فانتزی آن، روی میز آرایش یا شلف هدیه‌ای چشم‌گیر می‌سازد.", category: "organizers-decor", type: "جعبه جواهرات", sku: "3DM-ORG-008", price: 1090000, images: ["08-pink-bow-jewelry-box.png"], material: "پلاستیک چاپ سه‌بعدی", color: "صورتی پاستلی", style: "فانتزی رمانتیک", dimensions: "مناسب زیورآلات و خرده‌ریزهای سبک", useCases: "میز آرایش، هدیه، نظم‌دهی زیورآلات", care: "از قرار دادن اجسام نوک‌تیز داخل جعبه خودداری کنید.", tags: ["جعبه جواهرات", "پاپیون", "اکسسوری رومیزی"], features: ["درِ جداشونده", "بدنه طرح‌دار", "فرم گرد"] }),
  product({ title: "استند گوشواره رومیزی", handle: "earring-display-stand", short: "استند چندردیفه برای نمایش و نظم‌دهی گوشواره‌ها.", description: "استند گوشواره رومیزی با ردیف‌های سوراخ‌دار و قلاب‌های پایینی، نمایش و انتخاب گوشواره‌ها را ساده‌تر می‌کند. طراحی مینیمال آن برای میز آرایش، ویترین کوچک یا هدیه به علاقه‌مندان زیورآلات کاربردی است.", category: "organizers-decor", type: "استند زیورآلات", sku: "3DM-ORG-009", price: 1190000, images: ["09-earring-display-stand.png"], material: "پلاستیک چاپ سه‌بعدی", color: "سفید", style: "مینیمال کاربردی", dimensions: "چند ردیف برای گوشواره‌های سبک", useCases: "میز آرایش، ویترین، نظم‌دهی زیورآلات", care: "برای حفظ تعادل، روی سطح صاف قرار داده شود.", tags: ["استند گوشواره", "نظم‌دهنده", "زیورآلات"], features: ["چند ردیف نگهدارنده", "قلاب پایینی", "پایه پایدار"] }),
  product({ title: "جا انگشتری دایناسور گردن‌بلند", handle: "dinosaur-ring-holder", short: "نگهدارنده انگشتر با فرم دایناسور گردن‌بلند.", description: "جا انگشتری دایناسور گردن‌بلند با فرم بامزه و مینیمال، انگشترهای روزمره را در معرض دید نگه می‌دارد. گردن بلند آن برای قرار دادن حلقه مناسب است و روی میز کنار تخت یا میز آرایش جلوه‌ای دوست‌داشتنی دارد.", category: "organizers-decor", type: "جا انگشتری", sku: "3DM-ORG-010", price: 590000, images: ["10-dinosaur-ring-holder.png"], material: "پلاستیک چاپ سه‌بعدی", color: "کرم روشن", style: "فانتزی مینیمال", dimensions: "مناسب یک تا چند حلقه سبک", useCases: "میز آرایش، کنار تخت، هدیه", care: "برای حلقه‌های بسیار سنگین از پایه استفاده نکنید.", tags: ["جا انگشتری", "دایناسور", "دکور رومیزی"], features: ["گردن بلند نگهدارنده", "پایه چهارپا", "ابعاد جمع‌وجور"] }),
  product({ title: "درخت نگهدارنده جواهرات", handle: "tree-jewelry-organizer", short: "استند شاخه‌ای برای گردنبند، دستبند، حلقه و گوشواره.", description: "درخت نگهدارنده جواهرات با شاخه‌های متعدد و سینی چندضلعی در پایه، زیورآلات روزمره را مرتب و قابل‌دسترسی نگه می‌دارد. فرم درختی و دکوراتیو آن برای میز آرایش یا هدیه‌ای کاربردی و زیبا انتخاب مناسبی است.", category: "organizers-decor", type: "استند زیورآلات", sku: "3DM-ORG-011", price: 1590000, images: ["11-tree-jewelry-organizer.png"], material: "پلاستیک چاپ سه‌بعدی", color: "سفید", style: "طبیعی مینیمال", dimensions: "مناسب زیورآلات سبک روزمره", useCases: "میز آرایش، نظم‌دهی زیورآلات، هدیه", care: "گردنبندها را با فاصله آویزان کنید تا گره نخورند.", tags: ["استند جواهرات", "درختی", "نظم‌دهنده"], features: ["شاخه‌های چندگانه", "سینی پایه", "نمایش هم‌زمان زیورآلات"] }),
  product({ title: "اکسسوری موی گیاهی با پرنده", handle: "botanical-bird-hair-accessory", short: "اکسسوری موی شاخه‌ای با برگ، گل، پرنده و پروانه.", description: "اکسسوری موی گیاهی با شاخه‌های طبیعی، برگ‌های سرخسی، گل‌های کوچک، پرنده آبی و پروانه، برای استایل‌های رمانتیک و فانتزی طراحی شده است. گالری محصول، نمای استفاده، اجزای آن و جزئیات بافت را نشان می‌دهد.", category: "gift-hair-accessories", type: "اکسسوری مو", sku: "3DM-HAIR-012", price: 1390000, images: ["12-botanical-hair-stick-lifestyle.png", "13-botanical-hair-stick-parts.png", "14-botanical-hair-stick-detail.png"], material: "پلاستیک چاپ سه‌بعدی و گیره نگهدارنده", color: "سبز گیاهی، قهوه‌ای و چندرنگ", style: "بوهو و طبیعت‌گرا", dimensions: "مناسب شینیون و موهای جمع‌شده", useCases: "استایل روزمره، عکاسی، هدیه", care: "با فشار ملایم روی مو نصب شود و از خم‌کردن شاخه‌ها خودداری کنید.", tags: ["اکسسوری مو", "پرنده", "گل و برگ"], features: ["جزئیات گیاهی", "نمای استفاده", "اجزای قابل‌نصب"] }),
  product({ title: "نگهدارنده شینیون گربه‌ای", handle: "black-cat-bun-holder", short: "نگهدارنده شینیون گربه‌ای با چوب مو و چهره فانتزی.", description: "نگهدارنده شینیون گربه‌ای، دور گیسوی جمع‌شده قرار می‌گیرد و با چوب مو ثابت می‌شود. طراحی گوش‌ها، چشم‌های برجسته و بافت چاپی آن، یک اکسسوری مو متفاوت برای استایل روزمره و هدیه‌های خاص است.", category: "gift-hair-accessories", type: "اکسسوری مو", sku: "3DM-HAIR-013", price: 790000, images: ["15-black-cat-bun-holder.png", "16-cat-bun-holder-lifestyle.png"], material: "پلاستیک چاپ سه‌بعدی و چوب مو", color: "ذغالی و قهوه‌ای", style: "فانتزی گربه‌ای", dimensions: "مناسب شینیون متوسط", useCases: "استایل روزمره، هدیه، اکسسوری مو", care: "چوب مو را با زاویه ملایم وارد کنید و از فشار ناگهانی خودداری کنید.", tags: ["گربه", "شینیون", "اکسسوری مو"], features: ["چوب موی همراه", "فرم گربه‌ای", "نمای استفاده"] }),
  product({ title: "کیف دوشی قلب آناتومیک مشکی", handle: "black-anatomical-heart-bag", short: "کیف دوشی کلکسیونی با فرم قلب آناتومیک و زنجیر فلزی.", description: "کیف دوشی قلب آناتومیک مشکی با رگ‌های برجسته، فرم مجسمه‌وار و بند زنجیری، یک اکسسوری جسور و کلکسیونی است. این طرح برای استایل گوتیک، رویدادهای خاص یا هدیه به دوستداران آیتم‌های متفاوت مناسب است.", category: "gift-hair-accessories", type: "کیف کلکسیونی", sku: "3DM-BAG-014", price: 3490000, images: ["17-black-anatomical-heart-bag.png"], material: "پلاستیک چاپ سه‌بعدی و یراق فلزی", color: "مشکی مات", style: "گوتیک و دارک", dimensions: "مناسب لوازم کوچک و سبک", useCases: "استایل خاص، مهمانی، هدیه کلکسیونی", care: "با پارچه نرم تمیز شود و از قرار دادن وزن زیاد داخل کیف خودداری کنید.", tags: ["قلب آناتومیک", "کیف گوتیک", "اکسسوری دارک"], features: ["بند زنجیری", "رگ‌های برجسته", "فرم مجسمه‌وار"] }),
  product({ title: "جعبه قلب آناتومیک مشکی", handle: "black-anatomical-heart-box", short: "جعبه لولادار قلبی با فضای داخلی برای یادگاری‌های کوچک.", description: "جعبه قلب آناتومیک مشکی با درِ لولادار و بافت رگ‌های برجسته، یک ظرف دکوراتیو و کلکسیونی برای خرده‌ریزها یا یادگاری‌هاست. ظاهر دارک آن کنار کتاب، شلف یا میز کار، یک نقطه کانونی ایجاد می‌کند.", category: "organizers-decor", type: "جعبه دکوراتیو", sku: "3DM-DEC-015", price: 1590000, images: ["18-black-anatomical-heart-box.png"], material: "پلاستیک چاپ سه‌بعدی", color: "مشکی مات", style: "گوتیک و دارک", dimensions: "مناسب خرده‌ریزها و یادگاری‌های کوچک", useCases: "دکور شلف، جعبه یادگاری، هدیه", care: "لولا را با فشار کنترل‌شده باز و بسته کنید.", tags: ["قلب آناتومیک", "جعبه گوتیک", "دکور دارک"], features: ["درِ لولادار", "بافت رگ برجسته", "فضای داخلی"] }),
  product({ title: "مجسمه قلب آناتومیک قرمز", handle: "red-anatomical-heart-sculpture", short: "مجسمه قلب قرمز براق با جزئیات رگ‌های آناتومیک.", description: "مجسمه قلب آناتومیک قرمز، با فرم درشت و جزئیات برجسته، یک قطعه دکور جسور برای شلف، میز کار یا فضای گیمینگ است. رنگ قرمز براق و سطح لایه‌ای چاپ، آن را به هدیه‌ای کلکسیونی برای طرفداران دکور دارک تبدیل می‌کند.", category: "organizers-decor", type: "مجسمه دکوراتیو", sku: "3DM-DEC-016", price: 2290000, images: ["19-red-anatomical-heart-decor.png"], material: "پلاستیک چاپ سه‌بعدی", color: "قرمز براق", style: "آناتومیک و دارک", dimensions: "ابعاد دقیق هنگام ثبت سفارش هماهنگ می‌شود", useCases: "دکور شلف، میز کار، هدیه کلکسیونی", care: "با دستمال میکروفایبر خشک تمیز شود.", tags: ["قلب قرمز", "مجسمه آناتومیک", "دکور دارک"], features: ["جزئیات رگ برجسته", "پرداخت براق", "فرم ایستاده"] }),
  product({ title: "نیم‌تنه انیمه‌ای موخاردار", handle: "spiky-anime-head-bust", short: "نیم‌تنه کلکسیونی با مدل موی خاردار و استایل انیمه‌ای.", description: "نیم‌تنه انیمه‌ای موخاردار با تمرکز بر فرم پویا و لایه‌های متعدد مو، برای کلکسیونرهایی که ظاهر استایلایز شده انیمه را دوست دارند ساخته شده است. دو نمای محصول، جزئیات صورت و پشت سر را نشان می‌دهد.", category: "figures-collectibles", type: "نیم‌تنه کلکسیونی", sku: "3DM-FIG-017", price: 2390000, images: ["generated/spiky-anime-bust-color.png", "model-01-spiky-anime-head/01-front-three-quarter.png", "model-01-spiky-anime-head/02-alternate-view.png"], material: "رزین یا پلاستیک چاپ سه‌بعدی", color: "سفید مات", style: "انیمه", dimensions: "ابعاد دقیق هنگام ثبت سفارش هماهنگ می‌شود", useCases: "کلکسیون، شلف اتاق، هدیه انیمه", care: "با برس نرم، گردوغبار بین لایه‌های مو را پاک کنید.", tags: ["انیمه", "نیم‌تنه", "فیگور"], features: ["جزئیات موی خاردار", "دو نمای محصول", "مناسب رنگ‌آمیزی سفارشی"] }),
  product({ title: "خنجر بال‌دار فانتزی", handle: "winged-serpent-staff", short: "دکور دیواری یا رومیزی با بال‌ها و مارهای درهم‌تنیده.", description: "خنجر بال‌دار فانتزی با دو مار درهم‌تنیده و بال‌های پرجزئیات، از نمادهای اسطوره‌ای الهام گرفته است. برای دیوار گالری، شلف کلکسیون یا هدیه به علاقه‌مندان فانتزی و گوتیک گزینه‌ای چشم‌گیر است.", category: "figures-collectibles", type: "دکور کلکسیونی", sku: "3DM-COL-018", price: 1790000, images: ["generated/winged-serpent-staff-color.png", "model-02-winged-serpent-staff/01-front-three-quarter.png", "model-02-winged-serpent-staff/02-alternate-view.png"], material: "پلاستیک چاپ سه‌بعدی", color: "سفید مات", style: "فانتزی اسطوره‌ای", dimensions: "ابعاد دقیق هنگام ثبت سفارش هماهنگ می‌شود", useCases: "دکور دیوار، شلف کلکسیون، هدیه", care: "برای نصب یا جابه‌جایی، از بخش مرکزی نگه داشته شود.", tags: ["فانتزی", "اسطوره‌ای", "مار بال‌دار"], features: ["بال‌های برجسته", "جزئیات مار", "فرم کشیده"] }),
  product({ title: "استند دسته بازی پلی‌استیشن", handle: "playstation-controller-stands", short: "جفت استند رومیزی برای نگهداری و نمایش دسته بازی.", description: "استند دسته بازی با فرم زاویه‌دار و نماد الهام‌گرفته از پلی‌استیشن، دسته را مرتب و آماده استفاده نگه می‌دارد. گزینه‌ای مناسب برای تکمیل میز گیمینگ یا هدیه به گیمرها؛ سازگاری دقیق دسته پیش از خرید بررسی شود.", category: "desk-gaming", type: "استند کنترلر", sku: "3DM-GAME-019", price: 1190000, images: ["generated/playstation-controller-stands-color.png", "model-04-gaming-logo-stands/01-front-three-quarter.png", "model-04-gaming-logo-stands/02-alternate-view.png"], material: "پلاستیک چاپ سه‌بعدی", color: "خاکستری", style: "گیمینگ مدرن", dimensions: "مناسب کنترلرهای سازگار با فرم استند", useCases: "میز گیمینگ، نمایش کنترلر، هدیه", care: "روی سطح صاف قرار گیرد و از فشار جانبی به بازوها خودداری شود.", tags: ["استند کنترلر", "گیمینگ", "پلی‌استیشن"], features: ["جفت استند", "فرم زاویه‌دار", "نمایش مرتب کنترلر"] }),
  product({ title: "فیگور سرباز تاکتیکال ماسک‌دار", handle: "masked-tactical-soldier-figure", short: "فیگور کلکسیونی سرباز تاکتیکال با ماسک جمجمه و تجهیزات.", description: "فیگور سرباز تاکتیکال ماسک‌دار با جلیقه، تجهیزات و کلاه‌گوشی طراحی شده است. جزئیات لباس و پایه نمایش، آن را به انتخابی مناسب برای کلکسیون بازی‌های شوتر و دکور میز گیمینگ تبدیل می‌کند.", category: "figures-collectibles", type: "اکشن فیگور", sku: "3DM-FIG-020", price: 3290000, images: ["generated/tactical-soldier-color.png", "model-05-tactical-soldier/01-front-three-quarter.png", "model-05-tactical-soldier/02-rear-three-quarter.png"], material: "رزین یا پلاستیک چاپ سه‌بعدی", color: "خاکستری مات", style: "تاکتیکال گیمینگ", dimensions: "ابعاد دقیق هنگام ثبت سفارش هماهنگ می‌شود", useCases: "کلکسیون گیمینگ، دکور میز، هدیه", care: "برای جابه‌جایی از پایه و بدنه نگه دارید.", tags: ["سرباز تاکتیکال", "اکشن فیگور", "گیمینگ"], features: ["ماسک جمجمه", "جزئیات تجهیزات", "پایه نمایش"] }),
  product({ title: "فیگور غاز کارتونی", handle: "cartoon-goose-figure", short: "فیگور غاز کارتونی با فرم بامزه و ظاهر مینیمال.", description: "فیگور غاز کارتونی، انتخابی سبک و شوخ‌طبع برای میز کار، کتابخانه یا هدیه است. فرم گرد، پاهای کوچک و حالت چهره بازیگوش، آن را به یک دکور جمع‌وجور و دوست‌داشتنی تبدیل می‌کند.", category: "figures-collectibles", type: "فیگور دکوراتیو", sku: "3DM-FIG-021", price: 890000, images: ["model-06-cartoon-goose/01-front-three-quarter.png", "model-06-cartoon-goose/02-alternate-view.png"], material: "پلاستیک چاپ سه‌بعدی", color: "سفید مات", style: "کارتونی", dimensions: "ابعاد دقیق هنگام ثبت سفارش هماهنگ می‌شود", useCases: "دکور میز، هدیه، کلکسیون فانتزی", care: "با پارچه خشک تمیز شود.", tags: ["غاز", "کارتونی", "فیگور فانتزی"], features: ["فرم جمع‌وجور", "حالت چهره بامزه", "مناسب دکور"] }),
  product({ title: "نگهدارنده میله طرح جمجمه", handle: "gothic-skull-rod-holder", short: "نگهدارنده رومیزی گوتیک با فرم جمجمه و میله تزئینی.", description: "نگهدارنده میله طرح جمجمه با فرم گوتیک و جزئیات استخوانی، یک اکسسوری متفاوت برای میز کار، قلم‌های سبک یا شلف کلکسیون است. فرم خاص آن برای دکور دارک و هدیه به علاقه‌مندان ژانر وحشت مناسب است.", category: "desk-gaming", type: "نگهدارنده رومیزی", sku: "3DM-GAME-022", price: 1190000, images: ["model-07-skull-rod-holder/01-front-three-quarter.png", "model-07-skull-rod-holder/02-alternate-view.png"], material: "پلاستیک چاپ سه‌بعدی", color: "سفید مات", style: "گوتیک و ترسناک", dimensions: "مناسب ابزارهای سبک رومیزی", useCases: "میز گیمینگ، دکور دارک، هدیه", care: "از قراردادن ابزار سنگین روی میله خودداری کنید.", tags: ["جمجمه", "گوتیک", "نگهدارنده رومیزی"], features: ["فرم جمجمه", "میله تزئینی", "کاربری رومیزی"] }),
  product({ title: "جا قوطی طرح جیغ", handle: "scream-can-holder", short: "نگهدارنده قوطی نوشیدنی با چهره گوتیک و دسته تزئینی.", description: "جا قوطی طرح جیغ با چهره نقاب‌دار و دسته تزئینی، برای قوطی نوشیدنی یا استفاده به‌عنوان ظرف رومیزی سبک طراحی شده است. انتخابی دارک و متفاوت برای میز گیمینگ، شلف کلکسیون یا هدیه خاص.", category: "desk-gaming", type: "نگهدارنده قوطی", sku: "3DM-GAME-023", price: 1290000, images: ["model-12-scream-can-holder/01-front-three-quarter.png", "model-12-scream-can-holder/02-alternate-view.png"], material: "پلاستیک چاپ سه‌بعدی", color: "سفید مات", style: "گوتیک و ترسناک", dimensions: "مناسب قوطی با اندازه استاندارد؛ پیش از خرید بررسی شود", useCases: "میز گیمینگ، هدیه دارک، دکور رومیزی", care: "برای نوشیدنی داغ یا تماس طولانی با رطوبت طراحی نشده است.", tags: ["جا قوطی", "جیغ", "گوتیک"], features: ["دسته تزئینی", "چهره نقاب‌دار", "کاربری رومیزی"], character: "الهام‌گرفته از ژانر اسلشر" }),
  product({ title: "نیم‌تنه وایکینگ جنگجو", handle: "viking-warrior-bust", short: "نیم‌تنه کلکسیونی وایکینگ با زره، ریش و تبر.", description: "نیم‌تنه وایکینگ جنگجو با زره حکاکی‌شده، ریش پرجزئیات و تبر پشت شانه، برای کلکسیونرهای دنیای اساطیر شمالی ساخته شده است. این قطعه روی شلف یا میز کار، حس یک تندیس کوچک و قدرتمند ایجاد می‌کند.", category: "figures-collectibles", type: "نیم‌تنه کلکسیونی", sku: "3DM-FIG-023", price: 3490000, images: ["model-08-viking-bust/01-front-three-quarter.png", "model-08-viking-bust/02-alternate-view.png"], material: "رزین یا پلاستیک چاپ سه‌بعدی", color: "خاکستری سنگی", style: "وایکینگ و اسطوره‌ای", dimensions: "ابعاد دقیق هنگام ثبت سفارش هماهنگ می‌شود", useCases: "کلکسیون، دکور شلف، هدیه", care: "برای پاک‌کردن جزئیات زره و ریش از برس نرم استفاده کنید.", tags: ["وایکینگ", "نیم‌تنه", "اسطوره‌ای"], features: ["زره حکاکی‌شده", "تبر تزئینی", "جزئیات ریش"] }),
  product({ title: "فیگور لوفی کلاه‌حصیری", handle: "luffy-straw-hat-anime-bust", short: "فیگور کلکسیونی لوفی با کلاه حصیری و ژست خوش‌آمدگویی.", description: "فیگور لوفی کلاه‌حصیری با ژست باز و جزئیات لباس، برای طرفداران انیمه وان‌پیس طراحی شده است. این مدل برای شلف کلکسیون، میز کار یا هدیه به یک اوتاکوی دوست‌داشتنی، انتخابی شناخته‌شده و پرانرژی است.", category: "figures-collectibles", type: "فیگور انیمه", sku: "3DM-FIG-024", price: 2990000, images: ["model-09-straw-hat-anime-bust/01-front-three-quarter.png", "model-09-straw-hat-anime-bust/02-alternate-view.png"], material: "رزین یا پلاستیک چاپ سه‌بعدی", color: "سفید مات", style: "انیمه ماجراجویی", dimensions: "ابعاد دقیق هنگام ثبت سفارش هماهنگ می‌شود", useCases: "کلکسیون انیمه، دکور میز، هدیه", care: "با دستمال نرم تمیز شود و از تماس با نور شدید طولانی پرهیز شود.", tags: ["لوفی", "وان‌پیس", "انیمه"], features: ["کلاه حصیری", "ژست باز", "پایه نمایش"], character: "Monkey D. Luffy / One Piece" }),
  product({ title: "حلقه دکور جغد و بال", handle: "owl-wing-collector-wreath", short: "حلقه دکوراتیو با جغد، بال‌ها و بافت فانتزی.", description: "حلقه دکور جغد و بال با ساختاری پرجزئیات و فرم فانتزی، برای دیوار گالری، شلف کلکسیون یا قاب‌سازی مناسب است. حضور جغد و پرهای برجسته، آن را به قطعه‌ای متفاوت برای علاقه‌مندان دکورهای اسطوره‌ای تبدیل می‌کند.", category: "figures-collectibles", type: "دکور دیواری کلکسیونی", sku: "3DM-COL-025", price: 2190000, images: ["model-10-owl-wreath/01-front-three-quarter.png", "model-10-owl-wreath/02-alternate-view.png"], material: "پلاستیک چاپ سه‌بعدی", color: "سفید مات", style: "فانتزی اسطوره‌ای", dimensions: "ابعاد دقیق هنگام ثبت سفارش هماهنگ می‌شود", useCases: "دکور دیوار، شلف کلکسیونی، هدیه", care: "برای نصب، از تکیه‌گاه مناسب با وزن محصول استفاده کنید.", tags: ["جغد", "دکور دیواری", "فانتزی"], features: ["جزئیات پر و بال", "فرم حلقه‌ای", "مناسب قاب‌سازی"] }),
  product({ title: "استند کنترلر فوتبال آلمان", handle: "germany-football-controller-stand", short: "استند کنترلر با فرم فوتبال و نشان الهام‌گرفته از آلمان.", description: "استند کنترلر فوتبال آلمان، یک پایه رومیزی برای نمایش دسته بازی با فرم الهام‌گرفته از فوتبال است. برای میز گیمینگ یا هدیه به هواداران فوتبال، ترکیبی از علاقه ورزشی و اکسسوری کاربردی می‌سازد؛ سازگاری کنترلر پیش از خرید بررسی شود.", category: "desk-gaming", type: "استند کنترلر", sku: "3DM-GAME-026", price: 1290000, images: ["generated/fc26-germany-controller-stand-color.png", "model-11-fc26-germany-stand/01-front-three-quarter.png", "model-11-fc26-germany-stand/02-alternate-view.png"], material: "پلاستیک چاپ سه‌بعدی", color: "خاکستری", style: "فوتبال و گیمینگ", dimensions: "مناسب کنترلرهای سازگار با فرم استند", useCases: "میز گیمینگ، هدیه فوتبالی، نمایش کنترلر", care: "روی سطح صاف و دور از لبه میز قرار داده شود.", tags: ["فوتبال", "آلمان", "استند کنترلر"], features: ["طرح فوتبال", "پایه رومیزی", "فرم نمایشی"] }),
  product({ title: "سینی سیسیفوس کلکسیونی", handle: "sisyphus-collector-tray", short: "سینی دکوراتیو با پیکره سیسیفوس در حال حمل سنگ.", description: "سینی سیسیفوس کلکسیونی با پیکره‌ای در حال حمل سنگ، یک دکور مفهومی برای کلید، سکه، تاس یا خرده‌ریزهای میز کار است. ترکیب کاربردی سینی و روایت اسطوره‌ای، آن را به هدیه‌ای خاص برای علاقه‌مندان هنر و دکور تبدیل می‌کند.", category: "organizers-decor", type: "سینی دکوراتیو", sku: "3DM-DEC-027", price: 1690000, images: ["model-13-sisyphus-tray/01-front-three-quarter.png", "model-13-sisyphus-tray/02-alternate-view.png"], material: "پلاستیک چاپ سه‌بعدی", color: "خاکستری سنگی", style: "اسطوره‌ای مفهومی", dimensions: "مناسب خرده‌ریزهای رومیزی", useCases: "جای کلید، دکور میز، هدیه", care: "برای اشیای سبک استفاده شود و با پارچه خشک تمیز شود.", tags: ["سیسیفوس", "سینی دکوراتیو", "اسطوره‌ای"], features: ["پیکره برجسته", "کاسه کم‌عمق", "فرم مفهومی"] }),
  product({ title: "استند هندزفری توپ فوتبال", handle: "soccer-ball-headset-stand", short: "پایه نگهدارنده هدست با فرم توپ فوتبال.", description: "استند هندزفری توپ فوتبال، هدست را پس از بازی یا کار مرتب و در دسترس نگه می‌دارد. فرم توپ و پایه‌های پشتیبان، آن را به یک آیتم کاربردی برای میز گیمینگ یا هدیه به علاقه‌مندان فوتبال تبدیل می‌کند.", category: "desk-gaming", type: "استند هدست", sku: "3DM-GAME-028", price: 1590000, images: ["model-14-soccer-ball-seat/01-front-three-quarter.png", "model-14-soccer-ball-seat/02-alternate-view.png"], material: "پلاستیک چاپ سه‌بعدی", color: "خاکستری", style: "فوتبال و گیمینگ", dimensions: "مناسب هدست‌های روگوشی سبک تا متوسط", useCases: "میز گیمینگ، میز کار، هدیه فوتبالی", care: "هدست را به‌آرامی روی پایه قرار دهید.", tags: ["استند هدست", "فوتبال", "گیمینگ"], features: ["فرم توپ فوتبال", "پایه پایدار", "نمایش مرتب هدست"] }),
  product({ title: "استند کنترلر جام جهانی", handle: "world-cup-controller-stand", short: "استند کنترلر با فرم جام و پیکره‌های نگهدارنده.", description: "استند کنترلر جام جهانی با فرمی شبیه جام و پیکره‌های نگهدارنده، برای نمایش یک کنترلر روی میز گیمینگ طراحی شده است. ظاهر فوتبالی و مجسمه‌وار آن، گزینه‌ای خاص برای هدیه به گیمرها و هواداران فوتبال است؛ سازگاری کنترلر پیش از خرید بررسی شود.", category: "desk-gaming", type: "استند کنترلر", sku: "3DM-GAME-029", price: 1790000, images: ["model-18-world-cup-controller-stand/01-front-three-quarter.png", "model-18-world-cup-controller-stand/02-alternate-view.png"], material: "پلاستیک چاپ سه‌بعدی", color: "خاکستری", style: "فوتبال و گیمینگ", dimensions: "مناسب کنترلرهای سازگار با فرم استند", useCases: "میز گیمینگ، هدیه فوتبالی، کلکسیون", care: "روی سطح صاف قرار دهید و از فشار روی پیکره‌ها خودداری کنید.", tags: ["جام جهانی", "استند کنترلر", "فوتبال"], features: ["فرم جام", "پیکره‌های نگهدارنده", "نمایش رومیزی"] }),
  product({ title: "فیگور هالو نایت شمشیرزن", handle: "hollow-knight-swordsman-figure", short: "فیگور کلکسیونی هالو نایت با نقاب شاخ‌دار، شنل تیره و شمشیر.", description: "فیگور هالو نایت با سر شاخ‌دار، چشم‌های تیره، شنل سرمه‌ای و شمشیر باریک، حال‌وهوای جهان فانتزی بازی را به شلف کلکسیون می‌آورد. در گالری محصول، یک نمای کامل و یک نمای مقیاس روی دست دیده می‌شود تا فرم جمع‌وجور و جزئیات پایه بهتر مشخص باشد.", category: "figures-collectibles", type: "فیگور گیمینگ", sku: "3DM-FIG-030", price: 2490000, images: ["figures/hollow-knight/01-front.jpg", "figures/hollow-knight/02-scale-view.jpg"], material: "پلاستیک چاپ سه‌بعدی", color: "سفید، سرمه‌ای و مشکی", style: "فانتزی تاریک گیمینگ", dimensions: "ابعاد تقریبی در گالری مقیاس محصول قابل مشاهده است", useCases: "کلکسیون گیمینگ، دکور میز، هدیه", care: "برای حفظ جزئیات شمشیر و شاخ‌ها با پارچه نرم و خشک تمیز شود.", tags: ["هالو نایت", "Hollow Knight", "فیگور گیمینگ", "شمشیرزن"], features: ["پایه سنگی", "شنل تیره", "نمای مقیاس"], character: "Hollow Knight" }),
  product({ title: "فیگور رورونوا زورو سه‌شمشیری", handle: "roronoa-zoro-three-sword-figure", short: "فیگور پرجزئیات زورو با سه شمشیر و پایه صخره‌ای.", description: "فیگور رورونوا زورو در ژست ایستاده و مسلح، با سه شمشیر، پارچه‌ی لایه‌دار و پایه صخره‌ای طراحی شده است. پنج تصویر گالری، نمای رنگ‌شده و مدل خام را از روبه‌رو، کنار و پشت نشان می‌دهند تا جزئیات شمشیرها و لباس پیش از انتخاب روشن باشد.", category: "figures-collectibles", type: "اکشن فیگور انیمه", sku: "3DM-FIG-031", price: 4490000, images: ["figures/roronoa-zoro/01-color-and-unpainted.jpg", "figures/roronoa-zoro/02-rear-side.jpg", "figures/roronoa-zoro/03-rear.jpg", "figures/roronoa-zoro/04-front-unpainted.jpg", "figures/roronoa-zoro/05-front-color.jpg"], material: "رزین چاپ سه‌بعدی", color: "خاکستری با جزئیات سبز و رنگی", style: "انیمه اکشن", dimensions: "ابعاد دقیق هنگام ثبت سفارش هماهنگ می‌شود", useCases: "کلکسیون وان‌پیس، دکور شلف، هدیه انیمه", care: "هنگام جابه‌جایی، محصول را از پایه نگه دارید و به شمشیرها فشار وارد نکنید.", tags: ["زورو", "رورونوا زورو", "وان‌پیس", "One Piece", "اکشن فیگور"], features: ["سه شمشیر", "پایه صخره‌ای", "گالری چندزاویه"], character: "Roronoa Zoro / One Piece" }),
  product({ title: "فیگور دختر انیمه‌ای تابستانی", handle: "anime-summer-girl-figure", short: "فیگور ایستاده انیمه‌ای با لباس تابستانی و پایه گرد.", description: "فیگور دختر انیمه‌ای تابستانی با موهای کوتاه، لباس سبک و کفش‌های بنددار، فرمی ایستاده و متعادل روی پایه گرد دارد. این مدل با رنگ خنثی برای شخصی‌سازی رنگ یا نمایش به شکل خام چاپی، گزینه‌ای مناسب برای میز و شلف کلکسیون است.", category: "figures-collectibles", type: "فیگور انیمه", sku: "3DM-FIG-032", price: 2690000, images: ["figures/anime-summer-girl/01-front.jpg"], material: "رزین چاپ سه‌بعدی", color: "کرم روشن", style: "انیمه تابستانی", dimensions: "ابعاد دقیق هنگام ثبت سفارش هماهنگ می‌شود", useCases: "کلکسیون انیمه، دکور شلف، هدیه", care: "روی سطح صاف قرار گیرد و با برس نرم تمیز شود.", tags: ["فیگور دخترانه", "انیمه", "تابستانی", "کلکسیونی"], features: ["پایه گرد", "جزئیات لباس", "مناسب رنگ‌آمیزی" ] }),
  product({ title: "فیگور دختر انیمه‌ای زانو‌زده", handle: "anime-kneeling-girl-figure", short: "فیگور رومیزی دختر انیمه‌ای در حالت زانو‌زده با پایه گرد.", description: "این فیگور دختر انیمه‌ای در حالت زانو‌زده طراحی شده و با لباس چین‌دار و پایه گرد، جلوه‌ای آرام و کلکسیونی دارد. فرم آن برای نمایش روی میز کار، شلف اتاق یا تکمیل مجموعه فیگورهای انیمه مناسب است.", category: "figures-collectibles", type: "فیگور انیمه", sku: "3DM-FIG-033", price: 2890000, images: ["figures/anime-kneeling-girl/01-front.jpg"], material: "رزین چاپ سه‌بعدی", color: "خاکستری روشن", style: "انیمه رومیزی", dimensions: "ابعاد دقیق هنگام ثبت سفارش هماهنگ می‌شود", useCases: "کلکسیون انیمه، دکور میز، هدیه", care: "برای پاک‌سازی با دستمال نرم یا برس ظریف استفاده شود.", tags: ["فیگور دخترانه", "انیمه", "رومیزی", "کلکسیونی"], features: ["حالت زانو‌زده", "پایه گرد", "جزئیات لباس چین‌دار"] }),
  product({ title: "فیگور اسپایدرگوئن نشسته", handle: "spider-gwen-crouching-figure", short: "فیگور اسپایدرگوئن در ژست نشسته با هودی و پایه شهری.", description: "فیگور اسپایدرگوئن در ژست نشسته با هودی، جزئیات تارعنکبوتی و پایه‌ای الهام‌گرفته از سطح شهری ساخته شده است. گالری سه‌تصویری، نمونه رنگ‌شده و دو نمای چاپی را کنار هم نشان می‌دهد و برای طرفداران شخصیت‌های کمیک و مجموعه‌های ابرقهرمانی انتخابی چشم‌گیر است.", category: "figures-collectibles", type: "فیگور ابرقهرمانی", sku: "3DM-FIG-034", price: 3690000, images: ["figures/spider-gwen/01-color.jpg", "figures/spider-gwen/02-white.jpg", "figures/spider-gwen/03-gray.jpg"], material: "رزین چاپ سه‌بعدی", color: "سفید، مشکی و صورتی", style: "کمیک و ابرقهرمانی", dimensions: "ابعاد دقیق هنگام ثبت سفارش هماهنگ می‌شود", useCases: "کلکسیون کمیک، دکور میز، هدیه", care: "به بخش‌های ظریف هودی و انگشت‌ها فشار وارد نشود.", tags: ["اسپایدرگوئن", "Spider-Gwen", "مارول", "فیگور ابرقهرمانی"], features: ["ژست پویا", "پایه شهری", "نمای رنگی و خام"], character: "Spider-Gwen / Marvel" }),
  product({ title: "فیگور قهرمان زن با پایه شعله‌ای", handle: "flame-base-heroine-figure", short: "فیگور کلکسیونی قهرمان زن با لباس زرهی و پایه شعله‌ای.", description: "فیگور قهرمان زن با لباس زرهی، بوت بلند و پایه‌ای با خطوط شعله‌ای، برای کلکسیون‌های فانتزی و ابرقهرمانی طراحی شده است. یک تصویر محصول چاپ‌شده و یک رندر از فرم کامل آن در گالری قرار گرفته تا حجم پایه و جزئیات لباس بهتر دیده شوند.", category: "figures-collectibles", type: "فیگور کلکسیونی", sku: "3DM-FIG-035", price: 3190000, images: ["figures/flame-heroine/01-printed.jpg", "figures/flame-heroine/02-render.jpg"], material: "رزین چاپ سه‌بعدی", color: "کرم روشن", style: "فانتزی ابرقهرمانی", dimensions: "ابعاد دقیق هنگام ثبت سفارش هماهنگ می‌شود", useCases: "کلکسیون، دکور شلف، هدیه", care: "برای حفظ خطوط شعله‌ای پایه از تماس با اجسام نوک‌تیز خودداری شود.", tags: ["قهرمان زن", "فیگور فانتزی", "پایه شعله‌ای", "کلکسیونی"], features: ["پایه تزئینی", "جزئیات لباس زرهی", "نمای چاپ و رندر"] }),
  product({ title: "فیگور دختر انیمه‌ای با کت کوتاه", handle: "anime-jacket-girl-figure", short: "فیگور ایستاده دختر انیمه‌ای با کت کوتاه و موهای بلند.", description: "فیگور دختر انیمه‌ای با موهای بلند، کت کوتاه و بوت بلند، در حالتی ایستاده روی پایه بیضی نمایش داده می‌شود. دو نمای روبه‌رو و پشت در گالری، فرم لباس، مو و جزئیات پیکره را برای انتخاب مطمئن‌تر نشان می‌دهند.", category: "figures-collectibles", type: "فیگور انیمه", sku: "3DM-FIG-036", price: 2990000, images: ["figures/anime-jacket-girl/01-front.jpg", "figures/anime-jacket-girl/02-rear.jpg"], material: "رزین چاپ سه‌بعدی", color: "کرم روشن", style: "انیمه مدرن", dimensions: "ابعاد دقیق هنگام ثبت سفارش هماهنگ می‌شود", useCases: "کلکسیون انیمه، دکور شلف، هدیه", care: "برای جابه‌جایی از پایه نگه دارید و موهای بلند مدل را تحت فشار قرار ندهید.", tags: ["فیگور دخترانه", "انیمه", "کت کوتاه", "کلکسیونی"], features: ["نمای جلو و پشت", "پایه بیضی", "جزئیات مو و لباس"] }),
  product({ title: "فیگور اندروید ۱۸", handle: "android-18-dragon-ball-figure", short: "فیگور اندروید ۱۸ با استایل کلاسیک و سه نمای گالری.", description: "فیگور اندروید ۱۸ با مدل موی کوتاه، جلیقه، دامن و بوت بلند، یکی از شخصیت‌های شناخته‌شده دنیای دراگون بال را به شکل یک مدل کلکسیونی ایستاده بازآفرینی می‌کند. گالری رنگی و دو نمای جانبی و پشت، جزئیات کامل لباس و فرم پیکره را نشان می‌دهد.", category: "figures-collectibles", type: "فیگور انیمه", sku: "3DM-FIG-037", price: 3290000, images: ["figures/android-18/01-color.jpg", "figures/android-18/02-side.jpg", "figures/android-18/03-rear.jpg"], material: "رزین چاپ سه‌بعدی", color: "سفید، مشکی و خاکستری", style: "انیمه کلاسیک", dimensions: "ابعاد دقیق هنگام ثبت سفارش هماهنگ می‌شود", useCases: "کلکسیون دراگون بال، دکور شلف، هدیه", care: "برای پاک‌سازی از پارچه نرم استفاده کنید و به قسمت‌های باریک لباس فشار وارد نکنید.", tags: ["اندروید ۱۸", "Android 18", "دراگون بال", "Dragon Ball", "فیگور انیمه"], features: ["نمای رنگی", "نمای جانبی و پشت", "جزئیات لباس"], character: "Android 18 / Dragon Ball" }),
] satisfies CatalogProduct[]

const categories: Array<{ handle: Category; name: string; description: string }> = [
  { handle: "figures-collectibles", name: "فیگور و کلکسیونی", description: "فیگورها، اکشن فیگورها و مدل‌های شخصیت‌محور چاپ سه‌بعدی." },
  { handle: "desk-gaming", name: "گیمینگ و اکسسوری میز", description: "استند کنترلر، پایه هدست و اکسسوری‌های کاربردی برای ستاپ." },
  { handle: "organizers-decor", name: "کاربردی و دکوری", description: "نظم‌دهنده‌ها، نگهدارنده‌ها و مدل‌های تزئینی چاپ سه‌بعدی." },
  { handle: "gift-hair-accessories", name: "هدیه و اکسسوری", description: "اکسسوری‌های متفاوت و محصولات مناسب هدیه." },
]

export default async function seed3DMorty({ container }: { container: MedusaContainer }) {
  const logger = container.resolve(ContainerRegistrationKeys.LOGGER)
  const query = container.resolve(ContainerRegistrationKeys.QUERY) as any
  const { data: shippingProfiles } = await query.graph({ entity: "shipping_profile", fields: ["id"] })
  const { data: salesChannels } = await query.graph({ entity: "sales_channel", fields: ["id", "name"], filters: { name: "Default Sales Channel" } })
  const { data: regions } = await query.graph({ entity: "region", fields: ["id", "currency_code"] })
  if (regions[0] && regions[0].currency_code !== "irr") await updateRegionsWorkflow(container).run({ input: { selector: { id: regions[0].id }, update: { name: "ایران", currency_code: "irr" } } })

  const { data: existingProducts } = await query.graph({ entity: "product", fields: ["id"] })
  if (existingProducts.length) await deleteProductsWorkflow(container).run({ input: { ids: existingProducts.map((item: any) => item.id) } })
  const { data: existingCategories } = await query.graph({ entity: "product_category", fields: ["id"] })
  if (existingCategories.length) await deleteProductCategoriesWorkflow(container).run({ input: existingCategories.map((item: any) => item.id) })
  const { data: existingOptions } = await query.graph({ entity: "product_option", fields: ["id"] })
  if (existingOptions.length) await deleteProductOptionsWorkflow(container).run({ input: { ids: existingOptions.map((item: any) => item.id) } })
  const categoryByHandle: Record<string, { id: string }> = {}
  for (const category of categories) {
    const { data: existing } = await query.graph({ entity: "product_category", fields: ["id", "handle"], filters: { handle: category.handle } })
    categoryByHandle[category.handle] = existing[0] ?? (await createProductCategoriesWorkflow(container).run({ input: { product_categories: [{ ...category, is_active: true }] } })).result[0]
  }

  const option = async (title: string, values: string[]) => {
    return (await createProductOptionsWorkflow(container).run({ input: { product_options: [{ title, values }] } })).result[0]
  }
  const materialOption = await option("متریال", Array.from(new Set(products.map((item) => item.material))))
  const colorOption = await option("رنگ", Array.from(new Set(products.map((item) => item.color))))
  const typeOption = await option("نوع محصول", Array.from(new Set(products.map((item) => item.type))))

  await createProductsWorkflow(container).run({
    input: {
      products: products.map((item, index) => ({
        title: item.title, handle: item.handle, description: item.description, category_ids: [categoryByHandle[item.category].id],
        status: ProductStatus.PUBLISHED, shipping_profile_id: shippingProfiles[0]?.id,
        sales_channels: salesChannels[0]?.id ? [{ id: salesChannels[0].id }] : undefined,
        images: item.images.map((image) => ({ url: `${storefrontImageBase}/${image}` })),
        options: [{ id: materialOption.id }, { id: colorOption.id }, { id: typeOption.id }],
        variants: [{ title: "نسخه استاندارد", sku: item.sku, manage_inventory: false, options: { "متریال": item.material, "رنگ": item.color, "نوع محصول": item.type }, prices: [{ amount: item.price, currency_code: "irr" }] }],
        metadata: {
          brand: "3DMorty", catalog_group: item.category, product_type: item.type, short_description: item.short,
          full_description: item.description, material: item.material, color: item.color, style: item.style,
          print_material: item.material, print_technology: printTechnology(item.material), dimensions: item.dimensions,
          use_cases: item.useCases, care: item.care,
          tags: item.tags, features: item.features, character: item.character ?? "", seo_title: `${item.title} | 3DMorty`,
          seo_description: item.short, slug: item.handle, featured: index < 8,
          collectible: item.category === "figures-collectibles",
          articulated: /مفصلی|انعطاف|متحرک/.test(`${item.type} ${item.tags.join(" ")} ${item.features.join(" ")}`),
          functional: item.category !== "figures-collectibles",
          desktop_accessory: item.category === "desk-gaming" || /میز|هولدر|نگهدارنده/.test(`${item.type} ${item.useCases}`),
          gaming_accessory: item.category === "desk-gaming" && /گیم|کنترلر|PS5|هدست/.test(`${item.title} ${item.tags.join(" ")}`),
          decorative: item.category !== "desk-gaming" || /دکوری|مجسمه|فیگور/.test(`${item.type} ${item.useCases}`),
          compatibility: compatibilityFor(item),
          searchable_keywords: [item.title, item.type, item.material, item.style, item.useCases, item.character, ...item.tags].filter(Boolean),
        },
      })),
    },
  })

  await ensureLaunchPromotion(container, logger)

  logger.info(`3DMorty catalog ready: ${products.length} products in ${categories.length} categories.`)
}
